// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type NoteNote struct {
	ID         uuid.UUID     `json:"id"`
	UserID     uuid.UUID     `json:"user_id"`
	CategoryID uuid.NullUUID `json:"category_id"`
	Title      string        `json:"title"`
	Content    string        `json:"content"`
	Pinned     bool          `json:"pinned"`
	Priority   int32         `json:"priority"`
	UpdatedAt  time.Time     `json:"updated_at"`
	CreatedAt  time.Time     `json:"created_at"`
}
