// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type UserUser struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	UpdatedAt time.Time `json:"updated_at"`
	CreatedAt time.Time `json:"created_at"`
}
