// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/sergio-id/go-notes/cmd/user/config"
	grpc2 "github.com/sergio-id/go-notes/internal/user/delivery/grpc"
	"github.com/sergio-id/go-notes/internal/user/infrastructure/network"
	postgres2 "github.com/sergio-id/go-notes/internal/user/infrastructure/repository/postgres"
	"github.com/sergio-id/go-notes/internal/user/usecase"
	"github.com/sergio-id/go-notes/pkg/logger"
	"github.com/sergio-id/go-notes/pkg/postgres"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config, dbConnStr postgres.DBConnString, grpcServer *grpc.Server, log logger.Logger) (*App, func(), error) {
	dbEngine, cleanup, err := dbEngineFunc(dbConnStr, log)
	if err != nil {
		return nil, nil, err
	}
	userRepository := postgres2.NewUserRepo(dbEngine)
	userUseCase := usecase.NewUserUseCase(userRepository)
	authDomainService, err := network.NewGRPCAuthClient(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userServiceServer := grpc2.NewGRPCUserServer(grpcServer, cfg, userUseCase, authDomainService, log)
	app := New(cfg, dbEngine, userUseCase, userServiceServer, authDomainService, log)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

func dbEngineFunc(url postgres.DBConnString, log logger.Logger) (postgres.DBEngine, func(), error) {
	db, err := postgres.NewPostgresDB(url)
	if err != nil {
		return nil, nil, err
	}

	log.Infof("Connected to postgres: %s", url)

	return db, func() { db.Close() }, nil
}
