replicaCount: 1

authClient:
  url: auth:5001

pg:
  dsn_url: host=go-notes-postgresql user=postgres password=postgres dbname=postgres sslmode=disable

redis:
  addr: go-notes-redis-master:6379

image:
  repository: simple025/go-notes-note
  pullPolicy: IfNotPresent
  tag: "1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "note"

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001

service:
  type: ClusterIP
  port: 5002
  targetPort: 5002
