apiVersion: v1
kind: Service
metadata:
  name: "user"
  labels:
    {{- include "user.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "user.selectorLabels" . | nindent 4 }}
