apiVersion: v1
kind: Service
metadata:
  name: "category"
  labels:
    {{- include "category.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "category.selectorLabels" . | nindent 4 }}
