replicaCount: 1

userClient:
  url: "user:5004"

redis:
  addr: "redis:6379"

image:
  repository: simple025/go-notes-auth
  pullPolicy: IfNotPresent
  tag: "1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "auth"

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
   runAsNonRoot: true
   runAsUser: 1001
   runAsGroup: 1001

service:
  type: ClusterIP
  port: 5001
  targetPort: 5001
